added a demo video
Pwntus/voice-cloner pull request #1
Opened 2023-11-24 17:35 UTC by suhasasumukh

Hey there!

I have added a demo video from your twitter handle to the readme file so that users can easily understand how to use this cloner

2023-11-24 21:54 UTC, Pwntus requested changes
Thanks! I've left some comments on your proposed additions.

2023-11-24 21:54 UTC, Pwntus commented on README.md
> +<https://github.com/suhasasumukh/voice-cloner/assets/70210383/2fd79d23-f295-4354-a07e-ea094c93e26b>
Please make this point to the file in this repository. Also, use the following format to get the thumbnail included:
```
[![Demo](./readme-demo/thumbnail.png)](./readme-demo/demo.mp4 "Demo")
```

2023-11-24 21:54 UTC, Pwntus commented on readme-demo/thumbnil.png
Please rename to "thumbnail.png".

2023-11-25 13:44 UTC, suhasasumukh commented on README.md
> +<https://github.com/suhasasumukh/voice-cloner/assets/70210383/2fd79d23-f295-4354-a07e-ea094c93e26b>
sure i will add this and fix the typo

2023-11-25 13:48 UTC, suhasasumukh commented
I have fixed the changes you have asked me, please do check it :)

2023-11-27 11:22 UTC, merged

2023-11-27 11:22 UTC, Pwntus commented
Thank you!